name: biobb_wf_godmd
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_io==5.2.0
  - biobb_structure_utils==5.2.0
  - biobb_analysis==5.2.0
  - biobb_godmd==5.1.1
  - emboss
  - jupyter
  - nglview
  - simpletraj
